export const ListOfFilms = [
    {
        id: 1,
        Image: "assets/images/films/TheDarkKnight.jpg",
        Title: "Kỵ Sỹ Bóng Đêm",
        Year: "2008",
        Nation: "USA vs UK",
        Des: "Kỵ sĩ bóng đêm (tựa gốc tiếng Anh: The Dark Knight) là một bộ phim điện ảnh siêu anh hùng năm 2008 do Christopher Nolan làm đạo diễn, sản xuất và đồng biên kịch. Dựa trên nhân vật truyện tranh Người Dơi của DC Comics",
        Trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    },
    {
        id: 2,
        Image: "assets/images/films/titanic.jpg",
        Title: "Titanic",
        Year: "1997",
        Nation: "USA",
        Des: "Titanic là một bộ phim điện ảnh thuộc thể loại thảm họa xen lẫn với lãng mạn - sử thi - chính kịch của Mỹ công chiếu năm 1997 do James Cameron làm đạo diễn, viết kịch bản, sản xuất và hỗ trợ tài chính cho phần dựng phim",
        Trailer: "https://www.youtube.com/embed/kVrqfYjkTdQ",
    },
    {
        id: 3,
        Image: "assets/images/films/peaky-blinders.jpg",
        Title: "Peaky Blinders",
        Year: "2013",
        Nation: "UK",
        Des: "Một băng đảng khét tiếng xuất hiện ở Birmingham, Anh Quốc năm 1919. Cầm đầu băng là Tommy Shelby, tên trùm tội phạm khét tiếng muốn nổi lên bằng mọi giá",
        Trailer: "https://www.youtube.com/embed/oVzVdvGIC7U",
    },
    {
        id: 4,
        Image: "assets/images/films/gwtw.jpg",
        Title: "Cuốn theo chiều gió",
        Year: "1939",
        Nation: "USA",
        Des: "Cuốn theo chiều gió (tiếng Anh: Gone With the Wind) (1939) là bộ phim Mỹ, thuộc thể loại phim chính kịch-lãng mạn-sử thi, được phỏng theo tiểu thuyết cùng tên của Margaret Mitchell, xuất bản năm 1936",
        Trailer: "https://www.youtube.com/embed/0X94oZgJis4",
    },
    {
        id: 5,
        Image: "assets/images/films/f&f7.jpg",
        Title: "Quá Nhanh Quá Nguy Hiểm 7",
        Year: "2015",
        Nation: "USA",
        Des: "Fast & Furious 7 (còn được gọi là Furious 7 và Furious Seven) là một phim hành động năm 2015 của Mỹ. Đây là phần tiếp theo của bộ phim năm 2013 Fast & Furious 6 và cũng là bộ phim thứ bảy trong loạt phim Fast & Furious",
        Trailer: "https://www.youtube.com/embed/Skpu5HaVkOc",
    },
    {
        id: 6,
        Image: "assets/images/films/avatar.jpg",
        Title: "Avatar",
        Year: "2009",
        Nation: "USA",
        Des: "Avatar (2009) là một bộ phim khoa học viễn tưởng lấy bối cảnh vào giữa thế kỷ 22 khi con người đang định cư Pandora , một mặt trăng sinh sống tươi tốt của một người khổng lồ khí trong hệ sao Alpha Centauri , để khai thác khoáng chất có giá trị là unibtanium",
        Trailer: "https://www.youtube.com/embed/5PSNL1qE6VY",
    },
    {
        id: 7,
        Image: "assets/images/films/inception.jpg",
        Title: "Inception",
        Year: "2010",
        Nation: "USA vs UK",
        Des: "Một tên trộm đánh cắp bí mật của công ty thông qua việc sử dụng công nghệ chia sẻ giấc mơ được giao nhiệm vụ ngược lại là gieo một ý tưởng vào tâm trí của một CEO, nhưng quá khứ bi thảm của anh ta có thể khiến dự án và nhóm của anh ta rơi vào thảm họa",
        Trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
    },
    {
        id: 8,
        Image: "assets/images/films/lord-of-the-rings.jpg",
        Title: "Lord of the Rings: The Return of the King",
        Year: "2003",
        Nation: "UK vs New Zealand vs Germany",
        Des: "Lord of the Rings: The Return of the King là bộ phim điện ảnh phiêu lưu kỳ ảo của đạo diễn Peter Jackson. Đây là bộ phim kết thúc của bộ ba phim Chúa tể những chiếc nhẫn trước đó là Hiệp hội nhẫn thần (2001) và Hai tòa tháp (2002)",
        Trailer: "https://www.youtube.com/embed/r5X-hFf6Bwo",
    },
    {
        id: 9,
        Image: "assets/images/films/john-wick3.jpg",
        Title: "John Wick: Chapter 3 - Parabellum",
        Year: "2019",
        Nation: "USA",
        Des: "John Wick đang chạy trốn sau khi giết một thành viên của hội sát thủ quốc tế, và với cái giá 14 triệu đô la trên đầu, anh ta là mục tiêu của những người đàn ông và phụ nữ bị tấn công ở khắp mọi nơi",
        Trailer: "https://www.youtube.com/embed/M7XM597XO94",
    },
    {
        id: 9,
        Image: "assets/images/films/john-wick3.jpg",
        Title: "John Wick: Chapter 3 - Parabellum",
        Year: "2019",
        Nation: "USA",
        Des: "John Wick đang chạy trốn sau khi giết một thành viên của hội sát thủ quốc tế, và với cái giá 14 triệu đô la trên đầu, anh ta là mục tiêu của những người đàn ông và phụ nữ bị tấn công ở khắp mọi nơi",
        Trailer: "https://www.youtube.com/embed/M7XM597XO94",
    },
    {
        id: 9,
        Image: "assets/images/films/john-wick3.jpg",
        Title: "John Wick: Chapter 3 - Parabellum",
        Year: "2019",
        Nation: "USA",
        Des: "John Wick đang chạy trốn sau khi giết một thành viên của hội sát thủ quốc tế, và với cái giá 14 triệu đô la trên đầu, anh ta là mục tiêu của những người đàn ông và phụ nữ bị tấn công ở khắp mọi nơi",
        Trailer: "https://www.youtube.com/embed/M7XM597XO94",
    },
    {
        id: 9,
        Image: "assets/images/films/john-wick3.jpg",
        Title: "John Wick: Chapter 3 - Parabellum",
        Year: "2019",
        Nation: "USA",
        Des: "John Wick đang chạy trốn sau khi giết một thành viên của hội sát thủ quốc tế, và với cái giá 14 triệu đô la trên đầu, anh ta là mục tiêu của những người đàn ông và phụ nữ bị tấn công ở khắp mọi nơi",
        Trailer: "https://www.youtube.com/embed/M7XM597XO94",
    },
];
